export const enum Status {
  RESEARCHING = 'Researching',
  PENDINGAPPROVAL = 'Pending Approval',
  APPROVED = 'Approved',
  DECLINED = 'Declined'
}

export const statusList = [
  'Researching',
  'Pending Approval',
  'Approved',
  'Declined'
];

export const statesList = [
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming'
];

export const sizeList = [
  '1-10 employees',
  '11-50 employees',
  '51-200 employees',
  '201-500 employees',
  '501-1000 employees',
  '1001-5000 employees',
  '5001-10,000 employees',
  '10,001+ employees'
];

export const industryList = [
  'Aerospace',
  'Agriculture',
  'Fishing',
  'Timber',
  'Tobacco',
  'Pharmaceutical',
  'Software',
  'Consulting',
  'Construction',
  'Defense',
  'Education',
  'Energy',
  'Electrical power',
  'Petroleum',
  'Entertainment',
  'Financial services',
  'Insurance',
  'Food',
  'Fruit production',
  'Health care',
  'Hospitality',
  'Information',
  'Manufacturing',
  'Automotive',
  'Electronics',
  'Pulp and paper',
  'Steel',
  'Shipbuilding',
  'Mass media',
  'Film',
  'Music',
  'News media',
  'Publishing',
  'Mining',
  'Telecommunications',
  'Transport',
  'Water',
  'Service',
  'Other'
];

export const primaryColorScheme = {
  domain: [
    '#0188C2',
    '#004F70',
    '#4AFFFE',
    '#00b862',
    '#FFFC63',
    '#FDBD2D',
    '#FC8A25',
    '#FA4F1E',
    '#FA141B',
    '#BA38D1'
  ]
};
